// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPreferences():Promise<main.UserPreferences>;

export function Greet(arg1:string):Promise<string>;

export function SavePreferences(arg1:main.UserPreferences):Promise<void>;
